export {default as Home} from './Home';
export {default as Profile} from './Profile';
export {default as EditProfile} from './EditProfile';
export {default as Notifications} from './Notifications';
export {default as CustomerSupport} from './CustomerSupport';
export {default as About} from './About';
export {default as FAQ} from './FAQ';
export {default as Chats} from './chats';
export {default as ChatDetails} from './chats/Details';
